### ISSUE TITLE
Fix Figure 3 Legend for Proofs

### ISSUE THREAD

**Issue by davebridges** [BridgesLab/ObesityParticulateTreatment#15]
From copyeditor: 

> In the text and in the legend, you describe a part D in this figure, but this lettered part doesn’t exist in the figure (there is A, B, and C, no D). I’m guessing there was supposed to be a part D but for whatever reason was dropped from the figure, but the legend and text weren’t changed to reflect the revised figure. If you wouldn’t mind sending me a revised legend as well clarifying the part of the text that describes part D, I would greatly appreciate it.

Erin, can you answer this and send it to me.  I will forward to copyeditor early next week

**Comment by esteph16** [comment]
You will need to send the copy editor the new figure file. If you uploaded the TIFF files, for some reason figure three was missing panel D, but the Illustrator, PDF and PNG versions were correct. No need to change anything in the text of the manuscript, just send the updated figure.
